platform_home:
    path: /{page}
    defaults: { _controller: PlatformBundle:Advert:index, page: 1 }
    requirements:
        page: \d+

platform_view:
    path: /advert/{id}
    defaults: { _controller: PlatformBundle:Advert:view }
    requirements:
        id: \d+

platform_add:
    path: /add
    defaults: { _controller: PlatformBundle:Advert:add }

platform_edit:
    path: /edit/{id}
    defaults: { _controller: PlatformBundle:Advert:edit }
    requirements:
        id: \d+

platform_delete:
    path: /delete/{id}
    defaults: { _controller: PlatformBundle:Advert:delete }
    requirements:
        id: \d+

platform_test:
    path: /test
    defaults: { _controller: PlatformBundle:Advert:test }

question_list:
    path: /question
    defaults: {_controller: PlatformBundle:Question:index}

question_add:
    path: /question/add
    defaults: {_controller: PlatformBundle:Question:add}

question_edit:
    path: /question/edit/{id}
    defaults: {_controller: PlatformBundle:Question:edit}

question_delete:
    path: /question/delete/{id}
    defaults: {_controller: PlatformBundle:Question:delete}
