my_user:
    resource: "@MyUserBundle/Resources/config/routing.yml"
    prefix:   /user

platform:
    resource: "@PlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

app:
    resource: '@AppBundle/Controller/'
    type: annotation

