<?php

namespace PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($limit)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.advert', 'adv')
            ->addSelect('adv')
        ;
        $qb->orderBy('a.date', 'DESC');
        $qb->setMaxResults($limit);

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
